spring.application.name=kart-order

# env path setup
spring.config.import=optional:file:../.env[.properties]

# Supabase connection setup
spring.datasource.url=${SUPABASE_DB_URL}
spring.datasource.username=${SUPABASE_DB_USER}
spring.datasource.password=${SUPABASE_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# flyway migration setup
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.schemas=kart_order
spring.flyway.default-schema=kart_order
spring.flyway.create-schemas=true

# server setup
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.default_schema=kart_order
server.port=8083


# actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-components=always
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true

# external service call
catalog.service.base-url=http://localhost:8082

# kafka server
spring.kafka.bootstrap-servers=localhost:9092
kafka.topic.catalog-events=catalog.events.v1

# kafka consumer
spring.kafka.consumer.group-id=kart-order-inventory
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.value.default.type=com.kart.order.kafka.event.CatalogEvent,com.kart.order.kafka.event.DeliveryEvent
spring.kafka.consumer.properties.spring.json.trusted.packages=com.kart.order.kafka.event

# kafka producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false

kafka.topic.order-events = order.events.v1
kafka.topic.delivery-events = delivery.events.v1